// This is a skeleton starter React page generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import { PageParamsProvider as PageParamsProvider__ } from "@plasmicapp/react-web/lib/host";
import GlobalContextsProvider from "../components/plasmic/blank_project/PlasmicGlobalContextsProvider";
import { PlasmicHomepage } from "../components/plasmic/blank_project/PlasmicHomepage";
import { useRouter } from "next/router";
import { PlasmicQueryDataProvider } from "@plasmicapp/react-web/lib/query";
import { extractPlasmicQueryData } from "@plasmicapp/react-web/lib/prepass";

export const getStaticProps = async context => {
  const queryCache = await extractPlasmicQueryData(
    <PageParamsProvider__ route={"/"} params={context.params}>
      <PlasmicHomepage />
    </PageParamsProvider__>
  );
  return {
    props: { queryCache }
  };
};

function Homepage({ queryCache }) {
  // Use PlasmicHomepage to render this component as it was
  // designed in Plasmic, by activating the appropriate variants,
  // attaching the appropriate event handlers, etc.  You
  // can also install whatever React hooks you need here to manage state or
  // fetch data.
  //
  // Props you can pass into PlasmicHomepage are:
  // 1. Variants you want to activate,
  // 2. Contents for slots you want to fill,
  // 3. Overrides for any named node in the component to attach behavior and data,
  // 4. Props to set on the root node.
  return (
    <GlobalContextsProvider>
      <PlasmicQueryDataProvider prefetchedCache={queryCache}>
        <PageParamsProvider__
          route={useRouter()?.pathname}
          params={useRouter()?.query}
          query={useRouter()?.query}
        >
          <PlasmicHomepage />
        </PageParamsProvider__>
      </PlasmicQueryDataProvider>
    </GlobalContextsProvider>
  );
}

export default Homepage;
